item {
    name: "crushedrotation",
    id: 1,
    display_name: "crushedrotation"
}
item {
    name: "noCaprotation",
    id: 2,
    display_name: "noCaprotation"
}
item {
    name: "noDefectrotation",
    id: 3,
    display_name: "noDefectrotation"
}
item {
    name: "noLabelrotation",
    id: 4,
    display_name: "noLabelrotation"
}
